#!/bin/sh
set -e
getent group screensteward >/dev/null || addgroup --system screensteward
systemctl daemon-reload || true
systemd-tmpfiles --create /usr/lib/tmpfiles.d/screensteward-core.conf || true
exit 0
